//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XetuxProfit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class saArticulo
    {
        public string co_art { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public string art_des { get; set; }
        public string tipo { get; set; }
        public bool anulado { get; set; }
        public Nullable<System.DateTime> fecha_inac { get; set; }
        public string co_lin { get; set; }
        public string co_subl { get; set; }
        public string co_cat { get; set; }
        public string co_color { get; set; }
        public string co_ubicacion { get; set; }
        public string cod_proc { get; set; }
        public string item { get; set; }
        public string modelo { get; set; }
        public string @ref { get; set; }
        public bool generico { get; set; }
        public bool maneja_serial { get; set; }
        public bool maneja_lote { get; set; }
        public bool maneja_lote_venc { get; set; }
        public decimal margen_min { get; set; }
        public decimal margen_max { get; set; }
        public string tipo_imp { get; set; }
        public string tipo_imp2 { get; set; }
        public string tipo_imp3 { get; set; }
        public string co_reten { get; set; }
        public string garantia { get; set; }
        public decimal volumen { get; set; }
        public decimal peso { get; set; }
        public decimal stock_min { get; set; }
        public decimal stock_max { get; set; }
        public decimal stock_pedido { get; set; }
        public int relac_unidad { get; set; }
        public decimal punt_ven { get; set; }
        public decimal punt_cli { get; set; }
        public decimal lic_mon_ilc { get; set; }
        public decimal lic_capacidad { get; set; }
        public decimal lic_grado_al { get; set; }
        public string lic_tipo { get; set; }
        public bool prec_om { get; set; }
        public string comentario { get; set; }
        public string tipo_cos { get; set; }
        public decimal porc_margen_minimo { get; set; }
        public decimal porc_margen_maximo { get; set; }
        public decimal mont_comi { get; set; }
        public decimal porc_arancel { get; set; }
        public Nullable<int> numcom { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public string dis_cen { get; set; }
        public string reten_iva_tercero { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<decimal> aux_imp01 { get; set; }
    
        public virtual saProveedor saProveedor { get; set; }
    }
}
