//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XetuxProfit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class saProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saProveedor()
        {
            this.saArticulo = new HashSet<saArticulo>();
            this.saDocumentoCompra = new HashSet<saDocumentoCompra>();
            this.saDocumentoCompra1 = new HashSet<saDocumentoCompra>();
            this.saFacturaCompra = new HashSet<saFacturaCompra>();
            this.saProveedor1 = new HashSet<saProveedor>();
        }
    
        public string co_prov { get; set; }
        public string prov_des { get; set; }
        public string co_seg { get; set; }
        public string co_zon { get; set; }
        public string tip_pro { get; set; }
        public bool inactivo { get; set; }
        public string direc1 { get; set; }
        public string direc2 { get; set; }
        public string telefonos { get; set; }
        public string fax { get; set; }
        public string respons { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public decimal mont_cre { get; set; }
        public string co_mone { get; set; }
        public string cond_pag { get; set; }
        public int plaz_pag { get; set; }
        public decimal desc_ppago { get; set; }
        public decimal desc_glob { get; set; }
        public string rif { get; set; }
        public bool nacional { get; set; }
        public Nullable<int> numcom { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public string dis_cen { get; set; }
        public string nit { get; set; }
        public string email { get; set; }
        public string co_cta_ingr_egr { get; set; }
        public string comentario { get; set; }
        public int tipo_adi { get; set; }
        public string matriz { get; set; }
        public string co_tab { get; set; }
        public string tipo_per { get; set; }
        public string co_pais { get; set; }
        public string ciudad { get; set; }
        public string zip { get; set; }
        public string website { get; set; }
        public string formtype { get; set; }
        public string taxid { get; set; }
        public bool contribu_e { get; set; }
        public bool rete_regis_doc { get; set; }
        public decimal porc_esp { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public string email_alterno { get; set; }
        public bool sujeto_obj_retenISLR_auto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saArticulo> saArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoCompra> saDocumentoCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoCompra> saDocumentoCompra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saFacturaCompra> saFacturaCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saProveedor> saProveedor1 { get; set; }
        public virtual saProveedor saProveedor2 { get; set; }
    }
}
